apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.fullnameOverride }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      volume: {{ .Values.fullnameOverride }}
