apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.fullnameOverride }}-pv
  labels:
    volume: {{ .Values.fullnameOverride }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: {{ .Values.persistence.hostPath }}
    type: DirectoryOrCreate
