apiVersion: v1
kind: Secret
metadata:
  name: experimentai-secrets
type: Opaque
stringData:
  # Postgres
  POSTGRES_USER: <postgres_user>
  POSTGRES_PASSWORD: <postgres_pass>

  # MinIO
  root-user: <mlflow_minio_user>
  root-password: <mlflow_minio_pass>

  # MLflow
  MLFLOW_DB: <mlflow_db>
  MLFLOW_USER: <mlflow_user>
  MLFLOW_PASSWORD: <mlflow_password>
  AWS_ACCESS_KEY_ID: <mlflow_minio_user>
  AWS_SECRET_ACCESS_KEY: <mlflow_minio_pass>

  # Redis
  REDIS_PASSWORD: <airflow_redis_pass>

  # Airflow
  AIRFLOW_DB: <airflow_db>
  AIRFLOW_ROOT_USER: <airflow_user>
  AIRFLOW_ROOT_PASSWORD: <airflow_pass>
  AIRFLOW_ROOT_EMAIL: <admin_email>
  AIRFLOW_DAGS_FOLDER: /opt/airflow/dags

  # ExperimentAI
  EXPERIMENTAI_DB: <experimentai_db>
  JWT_SECRET_KEY: <jwt_secret>
  ADMIN_EMAIL: <experimentai_admin_email>
  ADMIN_PASSWORD: <experimentai_admin_pass>
  INTERNAL_HEALTH_TOKEN: <internal_health_token>
