apiVersion: v2

name: experimentai-chart

description: >
  A Helm chart for deploying the ExperimentAI API framework for AI Experimentation Platform.

type: application

version: 0.1.0

appVersion: "1.6.3"
