apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.airflowWeb.fullnameOverride }}-service
spec:
  selector:
    app: {{ .Values.airflowWeb.fullnameOverride }}
  ports:
    - port: {{ .Values.airflowWeb.service.port }}
      targetPort: {{ .Values.airflowWeb.service.port }}
      nodePort: {{ .Values.airflowWeb.service.nodePort }}
  type: {{ .Values.airflowWeb.service.type }}
