apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.airflowWeb.fullnameOverride }}-entrypoint
data:
  entrypoint.sh: |-
    #!/bin/sh
    set -e

    pip install apache-airflow-providers-fab

    # DOWNLOAD POSTGRES CLIENT (psql)
    apt-get update && \
    apt-get install -y curl postgresql-client

    # CREATE THE AIRFLOW DATABASE, IF IT DOESN'T EXIST
    export PGPASSWORD=$POSTGRES_PASSWORD
    psql -h timescaledb-service -U $POSTGRES_USER -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '$AIRFLOW_DB'" | grep -q 1 || \
    psql -h timescaledb-service -U $POSTGRES_USER -d postgres -c "CREATE DATABASE $AIRFLOW_DB"

    # LOAD DATABASE
    airflow db migrate

    # CREATE ADMIN USER
    airflow users create \
      --username "$AIRFLOW_ROOT_USER" \
      --firstname Admin \
      --lastname User \
      --role Admin \
      --email "$AIRFLOW_ROOT_EMAIL" \
      --password "$AIRFLOW_ROOT_PASSWORD" || true

    # START THE AIRFLOW WEBSERVER
    airflow api-server
