apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-redis-pvc" .Values.fullnameOverride }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.redis.master.persistence.size }}
  selector:
    matchLabels:
      volume: {{ printf "%s-redis" .Values.fullnameOverride }}
