apiVersion: v1
kind: Service
metadata:
  name: {{ include "experimentai-chart.fullname" . }}-service
  labels:
    {{- include "experimentai-chart.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "experimentai-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
