apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ printf "%s-minio-pv" .Values.fullnameOverride }}
  labels:
    volume: {{ printf "%s-minio" .Values.fullnameOverride }}
spec:
  capacity:
    storage: {{ .Values.minio.persistence.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: {{ .Values.minio.persistence.hostPath }}
    type: DirectoryOrCreate
