apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-minio-pvc" .Values.fullnameOverride }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size }}
  selector:
    matchLabels:
      volume: {{ printf "%s-minio" .Values.fullnameOverride }}
